[package]
name = "arch-satellite-derive-space"
version.workspace = true
authors = ["Arch Network <contact@arch.network>", "Saturn BTC <contact@saturnbtc.io>"]
repository = "https://github.com/Arch-Network/satellite"
license = "Apache-2.0"
description = "Satellite Derive macro to automatically calculate the size of a structure or an enum"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["extra-traits"] }
