[package]
name = "arch-satellite-derive-accounts"
version.workspace = true
authors = ["Arch Network <contact@arch.network>", "Saturn BTC <contact@saturnbtc.io>"]
repository = "https://github.com/Arch-Network/satellite"
license = "Apache-2.0"
description = "Satellite Derive macro for accounts"
edition.workspace = true

[lib]
proc-macro = true

[features]
allow-missing-optionals = ["arch-satellite-syn/allow-missing-optionals"]
satellite-debug = ["arch-satellite-syn/satellite-debug"]
idl-build = ["arch-satellite-syn/idl-build"]
init-if-needed = ["arch-satellite-syn/init-if-needed"]

[dependencies]
arch-satellite-syn = { workspace = true }
quote = "1"
syn = { version = "1", features = ["full"] }
