[package]
name = "transfer-hook"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "transfer_hook"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["arch-satellite-lang/idl-build", "arch-satellite-apl/idl-build"]

[dependencies]
arch-satellite-lang = { path = "../../../../../lang", features = ["interface-instructions"] }
arch-satellite-apl = { path = "../../../../../spl" }
spl-discriminator = "0.4"
spl-tlv-account-resolution = "0.9"
spl-transfer-hook-interface = "0.9"
