[package]
name = "arch-satellite-attribute-access-control"
version.workspace = true
authors = ["Arch Network <contact@arch.network>", "Saturn BTC <contact@saturnbtc.io>"]
repository = "https://github.com/Arch-Network/satellite"
license = "Apache-2.0"
description = "Satellite attribute macro for instruction access control"
edition.workspace = true

[lib]
proc-macro = true

[features]
satellite-debug = ["arch-satellite-syn/satellite-debug"]

[dependencies]
arch-satellite-syn = { workspace = true }
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
