[package]
name = "arch-satellite-lang"
version.workspace = true
authors = ["Arch Network <contact@arch.network>", "Saturn BTC <contact@saturnbtc.io>"]
repository = "https://github.com/Arch-Network/satellite"
edition.workspace = true
license = "Apache-2.0"
description = "Arch Network eDSL"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
allow-missing-optionals = ["arch-satellite-derive-accounts/allow-missing-optionals"]
satellite-debug = [
	"arch-satellite-attribute-access-control/satellite-debug",
	"arch-satellite-attribute-account/satellite-debug",
	"arch-satellite-attribute-constant/satellite-debug",
	"arch-satellite-attribute-error/satellite-debug",
	"arch-satellite-attribute-program/satellite-debug",
	"arch-satellite-derive-accounts/satellite-debug",
]
derive = []
event-cpi = ["arch-satellite-attribute-event/event-cpi"]
idl-build = [
	"arch-satellite-attribute-account/idl-build",
	"arch-satellite-attribute-constant/idl-build",
	"arch-satellite-attribute-error/idl-build",
	"arch-satellite-attribute-program/idl-build",
	"arch-satellite-derive-accounts/idl-build",
	"arch-satellite-derive-serde/idl-build",
	"arch-satellite-lang-idl/build",
]
init-if-needed = ["arch-satellite-derive-accounts/init-if-needed"]
interface-instructions = ["arch-satellite-attribute-program/interface-instructions"]
lazy-account = [
	"arch-satellite-attribute-account/lazy-account",
	"arch-satellite-derive-serde/lazy-account",
]

[dependencies]
arch-satellite-attribute-event = { workspace = true }
arch-satellite-attribute-access-control = { workspace = true }
arch-satellite-attribute-account = { workspace = true }
arch-satellite-attribute-constant = { workspace = true }
arch-satellite-attribute-error = { workspace = true }
arch-satellite-attribute-program = { workspace = true }
arch-satellite-derive-accounts = { workspace = true }
arch-satellite-derive-serde = { workspace = true }
arch-satellite-derive-space = { workspace = true }

# `arch-satellite-lang-idl` should only be included with `idl-build` feature
arch-satellite-lang-idl = { workspace = true, optional = true }

base64 = "0.21"
bincode = "1"
borsh = { version = "1.4.0" }
bytemuck = "1.14"
arch_program = { version = "0.8.4" }
thiserror = "1.0.61"
