[package]
name = "arch-satellite-derive-serde"
version.workspace = true
authors = ["Arch Network <contact@arch.network>", "Saturn BTC <contact@saturnbtc.io>"]
repository = "https://github.com/Arch-Network/satellite"
license = "Apache-2.0"
description = "Satellite Derive macro for serialization and deserialization"
edition.workspace = true

[lib]
proc-macro = true

[features]
idl-build = ["arch-satellite-syn/idl-build"]
lazy-account = []

[dependencies]
arch-satellite-syn = { workspace = true }
arch-satellite-borsh-derive-internal = { path = "../../../borsh-derive-internal", version = "0.11.0" }
proc-macro2 = "1"
syn = { version = "1", features = ["full"] }
quote = "1"
